name: API Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
      - .github/workflows/api-docker-image.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./api
      run: docker build . --tag dylanvdbrink/fifacm-api:$(date +%s) --tag dylanvdbrink/fifacm-api:latest
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Push the Docker image
      working-directory: ./api
      run: docker image push --all-tags dylanvdbrink/fifacm-api
